name: Update Checkov Severity Mapping

on:
  # schedule:
  #   - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  update-severity-mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout Checkov Docs Repository
        uses: actions/checkout@v4
        with:
          repository: hlxsites/prisma-cloud-docs
          path: checkov-docs

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.1.4"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run scraper script
        run: node scripts/checkovPolicyScrapper.js checkov-docs/docs/en/enterprise-edition/policy-reference

      - name: Debug - Print git status
        run: git status

      - name: Check for changes
        id: git_status
        run: |
          git add checkov_policy_severity.ts
          git status
          git diff --staged --exit-code || echo "changed=true" >> $GITHUB_ENV

      - name: Generate branch name
        run: echo "BRANCH_NAME=update-checkov-severity-$(date +%s)" >> $GITHUB_ENV

      - name: Debug - Print branch name
        run: echo $BRANCH_NAME

      - name: Commit changes
        if: env.changed == 'true'
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git checkout -b $BRANCH_NAME
          git commit -m "Update Checkov severity mapping"

      - name: Push changes
        if: env.changed == 'true'
        run: |
          git push origin HEAD

      - name: Create Pull Request
        if: env.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Checkov severity mapping"
          branch: ${{ env.BRANCH_NAME }}
          title: "Update Checkov severity mapping"
          body: "Automated update of Checkov severity mapping"
          labels: automated update
          base: main # Specify the base branch
