name: Update Checkov Severity Mapping

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  

jobs:
  update-severity-mapping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Remove old checkov-docs if exists
      run: rm -rf checkov-docs

    - name: Clone Checkov Docs Repository
      run: git clone https://github.com/hlxsites/prisma-cloud-docs checkov-docs

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run scraper script
      run: node scripts/checkovPolicyScrapper.js checkov-docs/docs/en/enterprise-edition/policy-reference
    
    - name: Debug - Print git status
      run: git status
      
    - name: Check for changes
      id: git_status
      run: |
        git add checkov_policy_severity.ts
        git status
        git diff --staged --exit-code || echo "::set-output name=changed::true"

    - name: Commit changes
      if: steps.git_status.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update Checkov severity mapping"
        git push origin main